### ISSUE TITLE
Is the horizontal axis inverted in set_pixel?

### ISSUE THREAD

**Issue by jayniz** [pimoroni/unicorn-hat-hd#2] opened 2017-06-24 15:04 UTC
When running the same code on a `unicornhat` and `unicornhathd`, I get a mirrored image on the `unicornhathd`. Is it just me?

**Comment by Gadgetoid** [comment] 2017-06-26 10:06
The horizontal/vertical axis should be the same on both Unicorn HD and Unicorn HAT HD; the top left pixel being (0,0), with the header orientated upwards.

What appears to differ, to my surprise as it happens, is rotation. Setting 90degrees rotation on UHHD causes 90 degrees of counter-clockwise rotation, rather than clockwise.

**Comment by jayniz** [comment] 2017-06-27 18:54
I whipped up a little [unicorn-hat-simulator](https://github.com/jayniz/unicorn-hat-sim) - it seems like the `unicornhat` demos are all running fine, but for the `unicornhathd` I have to rotate them by 180° 🤔

**Comment by njbbaer** [comment] 2017-08-20 06:20
I can confirm this issue. It appears the default rotation is set at 180°, if you manually set rotation to 0° it will be oriented correctly. Most of the examples do this.

I'd like to see a fix for it.

**Comment by Mutiny-Games** [comment] 2017-08-24 13:52
I think I have experienced this too. At first I thought I was, uh, tired when porting matrix. Then I rotated it and it looked better. 

Now I have tried the following

```
import time
#from unicorn_hat_sim import unicornhathd
import unicornhathd

class playfield(object):
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.clear()
        unicornhathd.rotation(0)

    def set_pixel(self,x,y,r,g,b):
        self.pixels[x][y] = [r,g,b]

    def show(self):
        for y in xrange(self.height):
            for x in xrange(self.width):
                unicornhathd.set_pixel(x,y,self.pixels[x][y][0],self.pixels[x][y][1],self.pixels[x][y][2])
                # print "x,y=("+str(x) + ","+str(y)+")"
        unicornhathd.show()

    def clear(self):
        self.pixels = [[[0 for i in xrange(3)] for x in xrange(self.width)] for y in xrange(self.height) ]

def drawmap():
    test.set_pixel(0,0,0,255,0)
    test.set_pixel(7,7,255,255,255)
    test.set_pixel(7,8,255,126,64)
    test.set_pixel(8,7,255,126,64)
    test.set_pixel(8,8,255,255,255)
    test.set_pixel(15,15,0,0,255)

test = playfield(16,16)
while True:
    for y in xrange(16):
        for x in xrange(16):
            test.clear()
            drawmap()
            test.set_pixel(x,y,255,0,0)
            test.show()
            time.sleep(0.05)
```

If you run this (sorry it's been hacked out of another project) with GPIO header at the top, USB/Net to the right, microUSB power to the bottom in the left corner then the red dot travels from top to bottom, left to right.

Change the line 
`test.set_pixel(x,y,255,0,0) `
to 
`test.set_pixel(y,x,255,0,0)`
and the red dot travels left to right, top to bottom as expected.

**Comment by Mutiny-Games** [comment] 2017-08-29 14:15
Gadgetoid said the origin (0,0) is at top left with the gpio header orientated upwards. But that is totally against my findings that the origin is at the bottom left with the board orientated the same way, (15,15) is the top right led.

**Comment by jayniz** [comment] 2017-08-29 14:48
paging dr. @Gadgetoid

**Comment by futekov** [comment] 2017-09-14 20:09
I can confirm that only the horizontal axis in inverted on my unicorn hat hd.
My rotation is `unicornhathd.rotation(0)`
`0,0` lights up my top right pixel, but that can't be fixed with rotation because `1,0` lights up the pixel to the left of `0,0` (so 0,0 and 1,0 activate the **last** two pixels on the first row).

A workaround I use is just using a new function:
```
def pxl(x, y, r, g, b):
    unicornhathd.set_pixel(abs(x - 15), y, r, g, b)

Probably it's a different/faulty batch.

**Comment by Mutiny-Games** [comment] 2017-09-17 02:04
I still think that if you position the Pi this way.
![image](https://user-images.githubusercontent.com/414453/30517364-9cccdc54-9b54-11e7-8533-ba0c485aaeab.png)
The origin (0,0) is at the bottom left , (15,15) is the top right led.

**Comment by Mutiny-Games** [comment] 2017-09-17 02:55
With the Pi this way (I think this is the orientation @Gadgetoid said)
![image](https://user-images.githubusercontent.com/414453/30517564-c54b10e0-9b5b-11e7-91fa-5853fa9b6e4c.png)
And this code:
```python
#!/usr/bin/env python
import time
import unicornhathd as uhhd
try:
   uhhd.rotation(90)
   width,height = uhhd.get_shape()
   uhhd.clear()
   for y in range(height):
       for x in range(width):
           uhhd.set_pixel(x,y,255,255,255)
           uhhd.show()
           time.sleep(.1)
       uhhd.clear()
except KeyboardInterrupt:
    pass
uhhd.off()
```
(0,0) is in the lower left and (15,15) in the upper right.

**Comment by futekov** [comment] 2017-10-08 04:50
The issue doesn't concern the rotation or where the origin point is.

The problem is that the Y axis is build correctly, but the X one is inverted, this simple demo and the result show clearly that the X is inverted in my case and no rotation will fix that.

``` python
#!/usr/bin/python
import unicornhathd
unicornhathd.rotation(0)
unicornhathd.brightness(0.5)

unicornhathd.set_pixel(0,0,255,255,255)
unicornhathd.set_pixel(1,0,255,0,0)
unicornhathd.set_pixel(15,0,255,255,255)
unicornhathd.show()
```

![pi-uhhd](https://user-images.githubusercontent.com/1493690/31313999-da6f4e3a-abfc-11e7-8c30-da1b7d7f44f4.jpg)

**Comment by futekov** [comment] 2017-10-08 08:30
What's wrong is either:
- the X axis is inverted (x = `abs(x - 15)` fixes my demo above*)
- the X and Y are swapped (replacing one with the other and rotating by 90 fixes my demo above*)

* by fix I mean the red pixel appearing next to the white pixel on the left

**Comment by Gadgetoid** [comment] 2017-11-20 16:55
Sorry for the radio silence, it's clear I need to look further into this. At this stage I'm loathe to make any fundamental changes to the way the pixels are mapped- since it may break existing user code- but if there is a mapping issue, I'll have to figure something out.

**Comment by carpaij** [comment] 2017-12-06 15:13
I have the same problem with the inverted X axis. It's easy to demonstrate when you play around with the the unicornpaint project.

**Comment by Gadgetoid** [comment] 2018-01-24 13:13
I've just applied some fixes for Unicorn Paint, since it was broken in quite a few ways, one of those fixes is to account for the inverted X which is definitely an issue.

I'll have to contrive a way to fix this without driving everyone bonkers! Perhaps fixing by default in a new 0.X.0 release and providing a way to turn on the legacy behaviour?

I need to add `set_pixels` too.

**Comment by ali1234** [comment] 2018-02-27 17:18
The camera example also mirrors the image horizontally so yes, something is off here. (Using the release version of this library from Raspbian repos.)

**Comment by Gadgetoid** [comment] 2018-03-07 11:21
I'm going to have to bite-the-bullet and switch the library over to a sensible mapping with a sensible default rotation. Adding to my imminent-to-do list.

**Comment by Gadgetoid** [comment] 2018-03-08 17:09
So it looks like, by default, it appears like the HAT is running with the "Unicorn HAT HD" text at the top, and the X axis running right to left.

My mistake is in writing to the numpy buffer:

```
_buf[int(x)][int(y)] = r, g, b
```

Should be:

```
_buf[int(y)][int(x)] = r, g, b
```

Because `_buf.reshape(768)` is squashing the buffer into the sequence of 48-byte rows understood by Unicorn HAT HD.

This corrects the orientation to the top left, with the 40-pin header at the top of the board.

It's still debatable whether `0,0` should be the top left. This can be corrected by running the rotated buffer through `numpy.fliplr`, making `0,0` the bottom left, which is correct for Cartesian coordinate systems using positive numbers for X and Y.

I've pushed the fixes to correct orientation and rotation into a new branch: https://github.com/pimoroni/unicorn-hat-hd/tree/coords

I'm now wondering if I'm duplicating effort by swapping x/y coordinates and also flipping. Have a play and let me know if it feels sane.

**Comment by ali1234** [comment] 2018-03-08 18:04
There is the issue of memory layout as well. If you make it buf[x,y] then this means the vertical pixels are next to each other in memory, and two horizontal pixels are strided by the height of the image. This means if you try to copy a whole image into the buffer it probably has to be axis swapped first, ie:

    buf[:] = np.swapaxes(image, 0, 1)

So, a random observation: SDL surfaces in python when converted to an ndarray use [x, y] but if you use the libraries built in memory viewer then it is [y, x] :(

**Comment by Gadgetoid** [comment] 2018-03-10 01:01
In that case I should switch to [x, y] and ensure the appropriate transforms are made just before outputting the flattened array for the device.

**Comment by ali1234** [comment] 2018-03-10 07:12
That means I will have to do the opposite in order to cancel it out.

**Comment by ali1234** [comment] 2018-03-10 09:06
I think the trick here is to use views whenever possible, ie np.rot90 and np.transpose. These don't move data in memory, they give you a reference to the array that rearranges writes on the fly when you write to it.

**Comment by Gadgetoid** [comment] 2018-03-15 11:34
I was aware of the concept of views in numpy, but didn't realise that `np.rot90`, for example, produced a view.  That means this view need only be generated once, when the rotation is set, and re-used in the draw method?

Right now the buffer is drawn into as `x, y`, rotated counter-clockwise  by the rotation amount + 1 to achieve the final rotation:

```python
numpy.rot90(_buf,-_rotation + 1)
```

Running my basic line example against these changes confirm they are sane at all rotations: https://github.com/pimoroni/unicorn-hat-hd/blob/coords/examples/line.py

**Comment by ali1234** [comment] 2018-03-15 19:44
Numpy tries to return a view whenever it possibly can because it is a very cheap operation to do and allows numpy to stay inside C code for longer.

In ugly I took the approach of keeping the internal buffer fixed and returning a view for the user to draw on. This means I don't ever have to worry about how to rotate when sending the data to the hardware, and so all that logic can live in the top level abstraction. And that's how I can churn out the drivers so fast. :)

I think for this specific case you want transpose rather than rot90. Transpose directly swaps X and Y ie it does a rotate and a flip.

**Closed** 2019-08-27 15:13 UTC
Labels: bug
